#ifndef _EXCEPTIONS_H
#define _EXCEPTIONS_H

#define E_JOY_OPEN 0x01
#define E_JOY_IOCTL_BUTTONS 0x02
#define E_JOY_IOCTL_AXES 0x03

#define E_JOY_EVENT_NUMBER_RANGE 0x04
#define E_JOY_EVENT_TYPE 0x05
#define E_JOY_READ 0x06

#define E_JOY_BUTTON_IDX_RANGE 0x07
#define E_JOY_AXIS_IDX_RANGE 0x08

#define E_XBOX_INVALID_HAND 0x10
#define E_XBOX_INVALID_POV 0x11

#define E_SPEED_DIO_RANGE 0x20
#define E_SPEED_DIO_JUMPER 0x21
#define E_SPEED_PWM_GENERATOR_ACTIVATION 0x22
#define E_SPEED_PWM_SET_DUTY_CYCLE 0x23

#define E_VMX_NOT_OPEN 0x31

#endif